//
// AppointmentsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AppointmentsAPI {

    /**
     * enum for parameter filterTense
     */
    public enum FilterTense_getAppointments: String, CaseIterable {
        case past = "PAST"
        case upcoming = "UPCOMING"
    }

    /**
     List all appointments.
     
     - parameter include: (query) Comma separated list of optional data to include in the response. (optional)
     - parameter filterTense: (query) Return appointments that are upcoming or in the past. (optional)
     - parameter filterStartAtGte: (query) Return appointments where the start_at field is greater than or equal to this value. Effectively, appointments that start after this date. (optional)
     - parameter filterStartAtLte: (query) Return appointments where the start_at field is less than or equal to this value. Effectively, appointments that start before this date. (optional)
     - parameter filterUserIds: (query) The IDs of users whose appointments will be retrieved. UUID Version 4. (optional)
     - parameter sort: (query) Comma separated list of fields used for sorting. Placing a minus symbol in front of a field name sorts in descending order. Defaults to &#x60;-start_at&#x60;. (optional)
     - parameter perPage: (query) The number of items per page. Defaults to 25. (optional)
     - parameter page: (query) The requested page. Defaults to 1. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAppointments(include: String? = nil, filterTense: FilterTense_getAppointments? = nil, filterStartAtGte: Date? = nil, filterStartAtLte: Date? = nil, filterUserIds: [UUID]? = nil, sort: String? = nil, perPage: String? = nil, page: String? = nil, apiResponseQueue: DispatchQueue = AryeoAPI.apiResponseQueue, completion: @escaping ((_ data: AppointmentCollection?, _ error: Error?) -> Void)) {
        getAppointmentsWithRequestBuilder(include: include, filterTense: filterTense, filterStartAtGte: filterStartAtGte, filterStartAtLte: filterStartAtLte, filterUserIds: filterUserIds, sort: sort, perPage: perPage, page: page).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List all appointments.
     - GET /appointments
     - List all appointments. By default, returns a list of appointments that have been scheduled and have not been canceled
     - BASIC:
       - type: http
       - name: Token
     - parameter include: (query) Comma separated list of optional data to include in the response. (optional)
     - parameter filterTense: (query) Return appointments that are upcoming or in the past. (optional)
     - parameter filterStartAtGte: (query) Return appointments where the start_at field is greater than or equal to this value. Effectively, appointments that start after this date. (optional)
     - parameter filterStartAtLte: (query) Return appointments where the start_at field is less than or equal to this value. Effectively, appointments that start before this date. (optional)
     - parameter filterUserIds: (query) The IDs of users whose appointments will be retrieved. UUID Version 4. (optional)
     - parameter sort: (query) Comma separated list of fields used for sorting. Placing a minus symbol in front of a field name sorts in descending order. Defaults to &#x60;-start_at&#x60;. (optional)
     - parameter perPage: (query) The number of items per page. Defaults to 25. (optional)
     - parameter page: (query) The requested page. Defaults to 1. (optional)
     - returns: RequestBuilder<AppointmentCollection> 
     */
    open class func getAppointmentsWithRequestBuilder(include: String? = nil, filterTense: FilterTense_getAppointments? = nil, filterStartAtGte: Date? = nil, filterStartAtLte: Date? = nil, filterUserIds: [UUID]? = nil, sort: String? = nil, perPage: String? = nil, page: String? = nil) -> RequestBuilder<AppointmentCollection> {
        let localVariablePath = "/appointments"
        let localVariableURLString = AryeoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "include": include?.encodeToJSON(),
            "filter[tense]": filterTense?.encodeToJSON(),
            "filter[start_at_gte]": filterStartAtGte?.encodeToJSON(),
            "filter[start_at_lte]": filterStartAtLte?.encodeToJSON(),
            "filter[user_ids]": filterUserIds?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
            "per_page": perPage?.encodeToJSON(),
            "page": page?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppointmentCollection>.Type = AryeoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     List all unconfirmed appointments.
     
     - parameter include: (query) Comma separated list of optional data to include in the response. (optional)
     - parameter filterUserIds: (query) The IDs of users whose appointments will be retrieved. UUID Version 4. (optional)
     - parameter sort: (query) Comma separated list of fields used for sorting. Placing a minus symbol in front of a field name sorts in descending order. Defaults to &#x60;-start_at&#x60;. (optional)
     - parameter perPage: (query) The number of items per page. Defaults to 25. (optional)
     - parameter page: (query) The requested page. Defaults to 1. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUnconfirmedAppointments(include: String? = nil, filterUserIds: [UUID]? = nil, sort: String? = nil, perPage: String? = nil, page: String? = nil, apiResponseQueue: DispatchQueue = AryeoAPI.apiResponseQueue, completion: @escaping ((_ data: UnconfirmedAppointmentCollection?, _ error: Error?) -> Void)) {
        getUnconfirmedAppointmentsWithRequestBuilder(include: include, filterUserIds: filterUserIds, sort: sort, perPage: perPage, page: page).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List all unconfirmed appointments.
     - GET /unconfirmed-appointments
     - List all unconfirmed appointments. These are appointments that have not been scheduled. 
     - BASIC:
       - type: http
       - name: Token
     - parameter include: (query) Comma separated list of optional data to include in the response. (optional)
     - parameter filterUserIds: (query) The IDs of users whose appointments will be retrieved. UUID Version 4. (optional)
     - parameter sort: (query) Comma separated list of fields used for sorting. Placing a minus symbol in front of a field name sorts in descending order. Defaults to &#x60;-start_at&#x60;. (optional)
     - parameter perPage: (query) The number of items per page. Defaults to 25. (optional)
     - parameter page: (query) The requested page. Defaults to 1. (optional)
     - returns: RequestBuilder<UnconfirmedAppointmentCollection> 
     */
    open class func getUnconfirmedAppointmentsWithRequestBuilder(include: String? = nil, filterUserIds: [UUID]? = nil, sort: String? = nil, perPage: String? = nil, page: String? = nil) -> RequestBuilder<UnconfirmedAppointmentCollection> {
        let localVariablePath = "/unconfirmed-appointments"
        let localVariableURLString = AryeoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "include": include?.encodeToJSON(),
            "filter[user_ids]": filterUserIds?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
            "per_page": perPage?.encodeToJSON(),
            "page": page?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UnconfirmedAppointmentCollection>.Type = AryeoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Retrieve an unconfirmed appointment.
     
     - parameter unconfirmedAppointmentId: (path) The ID of an appointment. 
     - parameter include: (query) Comma separated list of optional data to include in the response. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUnconfirmedAppointmentsId(unconfirmedAppointmentId: UUID, include: String? = nil, apiResponseQueue: DispatchQueue = AryeoAPI.apiResponseQueue, completion: @escaping ((_ data: UnconfirmedAppointmentResource?, _ error: Error?) -> Void)) {
        getUnconfirmedAppointmentsIdWithRequestBuilder(unconfirmedAppointmentId: unconfirmedAppointmentId, include: include).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Retrieve an unconfirmed appointment.
     - GET /unconfirmed-appointments/{unconfirmed_appointment_id}
     - Retrieves the details of an unconfirmed appointment with the given ID.
     - BASIC:
       - type: http
       - name: Token
     - parameter unconfirmedAppointmentId: (path) The ID of an appointment. 
     - parameter include: (query) Comma separated list of optional data to include in the response. (optional)
     - returns: RequestBuilder<UnconfirmedAppointmentResource> 
     */
    open class func getUnconfirmedAppointmentsIdWithRequestBuilder(unconfirmedAppointmentId: UUID, include: String? = nil) -> RequestBuilder<UnconfirmedAppointmentResource> {
        var localVariablePath = "/unconfirmed-appointments/{unconfirmed_appointment_id}"
        let unconfirmedAppointmentIdPreEscape = "\(APIHelper.mapValueToPathItem(unconfirmedAppointmentId))"
        let unconfirmedAppointmentIdPostEscape = unconfirmedAppointmentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{unconfirmed_appointment_id}", with: unconfirmedAppointmentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = AryeoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "include": include?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UnconfirmedAppointmentResource>.Type = AryeoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Cancel an appointment.
     
     - parameter appointmentId: (path) The ID of an appointment. 
     - parameter appointmentCancelPutPayload: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func putAppointmentsAppointmentIdCancel(appointmentId: UUID, appointmentCancelPutPayload: AppointmentCancelPutPayload? = nil, apiResponseQueue: DispatchQueue = AryeoAPI.apiResponseQueue, completion: @escaping ((_ data: AppointmentResource?, _ error: Error?) -> Void)) {
        putAppointmentsAppointmentIdCancelWithRequestBuilder(appointmentId: appointmentId, appointmentCancelPutPayload: appointmentCancelPutPayload).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Cancel an appointment.
     - PUT /appointments/{appointment_id}/cancel
     - Cancel an appointment. The appointments order's customer can be optionally notified of this change. 
     - BASIC:
       - type: http
       - name: Token
     - parameter appointmentId: (path) The ID of an appointment. 
     - parameter appointmentCancelPutPayload: (body)  (optional)
     - returns: RequestBuilder<AppointmentResource> 
     */
    open class func putAppointmentsAppointmentIdCancelWithRequestBuilder(appointmentId: UUID, appointmentCancelPutPayload: AppointmentCancelPutPayload? = nil) -> RequestBuilder<AppointmentResource> {
        var localVariablePath = "/appointments/{appointment_id}/cancel"
        let appointmentIdPreEscape = "\(APIHelper.mapValueToPathItem(appointmentId))"
        let appointmentIdPostEscape = appointmentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{appointment_id}", with: appointmentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = AryeoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appointmentCancelPutPayload)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppointmentResource>.Type = AryeoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Reschedule an appointment.
     
     - parameter appointmentId: (path) The ID of an appointment. 
     - parameter appointmentReschedulePutPayload: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func putAppointmentsAppointmentIdReschedule(appointmentId: UUID, appointmentReschedulePutPayload: AppointmentReschedulePutPayload? = nil, apiResponseQueue: DispatchQueue = AryeoAPI.apiResponseQueue, completion: @escaping ((_ data: AppointmentResource?, _ error: Error?) -> Void)) {
        putAppointmentsAppointmentIdRescheduleWithRequestBuilder(appointmentId: appointmentId, appointmentReschedulePutPayload: appointmentReschedulePutPayload).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Reschedule an appointment.
     - PUT /appointments/{appointment_id}/reschedule
     - Reschedule an appointment. The appointments order's customer can be optionally notified of this change. 
     - BASIC:
       - type: http
       - name: Token
     - parameter appointmentId: (path) The ID of an appointment. 
     - parameter appointmentReschedulePutPayload: (body)  (optional)
     - returns: RequestBuilder<AppointmentResource> 
     */
    open class func putAppointmentsAppointmentIdRescheduleWithRequestBuilder(appointmentId: UUID, appointmentReschedulePutPayload: AppointmentReschedulePutPayload? = nil) -> RequestBuilder<AppointmentResource> {
        var localVariablePath = "/appointments/{appointment_id}/reschedule"
        let appointmentIdPreEscape = "\(APIHelper.mapValueToPathItem(appointmentId))"
        let appointmentIdPostEscape = appointmentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{appointment_id}", with: appointmentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = AryeoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appointmentReschedulePutPayload)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppointmentResource>.Type = AryeoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
