name: Aryeo
targets:
  Aryeo:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [Aryeo]
    info:
      path: ./Info.plist
      version: 
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
