//
// AppointmentCancelPutPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for canceling an appointment record. */
public struct AppointmentCancelPutPayload: Codable {

    /** Sends a notification to the appointment's order's customer that the appointment was canceled. */
    public private(set) var notifyCustomer: Bool?

    public init(notifyCustomer: Bool? = nil) {
        self.notifyCustomer = notifyCustomer
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notifyCustomer = "notify_customer"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notifyCustomer, forKey: .notifyCustomer)
    }
}

