//
// CalendarDay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A bookable time range with available users. */
public struct CalendarDay: Codable {

    /** Calendar day that has available timeslots. */
    public private(set) var date: String
    /** Does the day have availability? */
    public private(set) var isAvailable: Bool

    public init(date: String, isAvailable: Bool) {
        self.date = date
        self.isAvailable = isAvailable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case isAvailable = "is_available"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(isAvailable, forKey: .isAvailable)
    }
}

