//
// Currency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A system of money used for payment. */
public struct Currency: Codable, Hashable {

    /** The ID of the currency. */
    public var id: String
    /** The name of the currency. */
    public var name: String
    /** The currency symbol. */
    public var symbol: String
    /** Is this currency enabled for Aryeo? */
    public var enabled: Bool

    public init(id: String, name: String, symbol: String, enabled: Bool) {
        self.id = id
        self.name = name
        self.symbol = symbol
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case symbol
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(enabled, forKey: .enabled)
    }
}

