//
// Image.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A visual representation of something. */
public struct Image: Codable {

    /** ID of the image. UUID Version 4. */
    public private(set) var id: UUID
    /** A URL for a thumbnail-sized version of the image. */
    public private(set) var thumbnailUrl: String
    /** A URL for a large version of the image. */
    public private(set) var largeUrl: String
    /** A URL for the original, full-resolution version of the image. Useful for downloading. */
    public private(set) var originalUrl: String
    /** The order in which the image should be displayed amongst other related images. */
    public private(set) var index: Int?
    /** A brief explanation of the image. */
    public private(set) var caption: String?
    /** Should the image be displayed in a gallery? */
    public private(set) var displayInGallery: Bool

    public init(id: UUID, thumbnailUrl: String, largeUrl: String, originalUrl: String, index: Int? = nil, caption: String? = nil, displayInGallery: Bool) {
        self.id = id
        self.thumbnailUrl = thumbnailUrl
        self.largeUrl = largeUrl
        self.originalUrl = originalUrl
        self.index = index
        self.caption = caption
        self.displayInGallery = displayInGallery
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case thumbnailUrl = "thumbnail_url"
        case largeUrl = "large_url"
        case originalUrl = "original_url"
        case index
        case caption
        case displayInGallery = "display_in_gallery"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(thumbnailUrl, forKey: .thumbnailUrl)
        try container.encode(largeUrl, forKey: .largeUrl)
        try container.encode(originalUrl, forKey: .originalUrl)
        try container.encodeIfPresent(index, forKey: .index)
        try container.encodeIfPresent(caption, forKey: .caption)
        try container.encode(displayInGallery, forKey: .displayInGallery)
    }
}

