//
// MarketingMaterialPublishPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for publishing a marketing material record. */
public struct MarketingMaterialPublishPayload: Codable, Hashable {

    /** String representation of a polotno JSON object. */
    public var polotnoJson: String?

    public init(polotnoJson: String? = nil) {
        self.polotnoJson = polotnoJson
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case polotnoJson = "polotno_json"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(polotnoJson, forKey: .polotnoJson)
    }
}

