//
// OrderPostPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for creating an order. */
public struct OrderPostPayload: Codable {

    public enum FulfillmentStatus: String, Codable, CaseIterable {
        case fulfilled = "FULFILLED"
        case unfulfilled = "UNFULFILLED"
    }
    /** The fulfillment status of the order. Defaults to \"UNFULFILLED\". */
    public private(set) var fulfillmentStatus: FulfillmentStatus?
    /** Internal notes that will be attached to the order. Viewable only by the team. */
    public private(set) var internalNotes: String?
    /** ID of the address to associate with the order. UUID Version 4. */
    public private(set) var addressId: UUID?
    /** ID of the customer to associate with the order. UUID Version 4. */
    public private(set) var customerId: UUID?
    /** Indicates if the customer and creator notifications should be sent when creating the order. Requires an address and customer to be set in order for the notifications to be sent. */
    public private(set) var notify: Bool?

    public init(fulfillmentStatus: FulfillmentStatus? = nil, internalNotes: String? = nil, addressId: UUID? = nil, customerId: UUID? = nil, notify: Bool? = nil) {
        self.fulfillmentStatus = fulfillmentStatus
        self.internalNotes = internalNotes
        self.addressId = addressId
        self.customerId = customerId
        self.notify = notify
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fulfillmentStatus = "fulfillment_status"
        case internalNotes = "internal_notes"
        case addressId = "address_id"
        case customerId = "customer_id"
        case notify
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fulfillmentStatus, forKey: .fulfillmentStatus)
        try container.encodeIfPresent(internalNotes, forKey: .internalNotes)
        try container.encodeIfPresent(addressId, forKey: .addressId)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(notify, forKey: .notify)
    }
}

