//
// OrderForm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A mechanism for placing new orders on the Aryeo platform.  */
public struct OrderForm: Codable, Hashable {

    /** UUID of the order form. */
    public var id: UUID
    /** The name of the order form. */
    public var name: String?
    /** A URL of a publicly-accessible webpage for this order form. */
    public var url: String

    public init(id: UUID, name: String? = nil, url: String) {
        self.id = id
        self.name = name
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(url, forKey: .url)
    }
}

