//
// Order.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A payment request for some content or service. */
public struct Order: Codable {

    public enum FulfillmentStatus: String, Codable, CaseIterable {
        case fulfilled = "FULFILLED"
        case unfulfilled = "UNFULFILLED"
    }
    public enum PaymentStatus: String, Codable, CaseIterable {
        case paid = "PAID"
        case unpaid = "UNPAID"
    }
    public enum Currency: String, Codable, CaseIterable {
        case usd = "USD"
        case cad = "CAD"
        case gbp = "GBP"
        case chf = "CHF"
        case eur = "EUR"
        case aud = "AUD"
        case nzd = "NZD"
        case zar = "ZAR"
    }
    /** ID of the order. UUID Version 4. */
    public private(set) var id: UUID
    /** A vanity id used for internal tracking of orders for a given vendor. */
    public private(set) var number: Int
    /** The title of the order, generated by combining the order's number property with the prefix \"Order #\". */
    public private(set) var title: String
    /** The fulfillment status of the order. */
    public private(set) var fulfillmentStatus: FulfillmentStatus
    /** The payment status of the order. */
    public private(set) var paymentStatus: PaymentStatus
    /** The three-letter ISO 4217 currency code for the currency in which this order was or will be transacted. Must be a supported currency of Aryeo. */
    public private(set) var currency: Currency?
    /** A positive integer in the smallest currency unit (that is, 100 cents for $1.00) representing the total order amount that was or will be charged. This accounts for order items and taxes.  */
    public private(set) var totalAmount: Int?
    /** A URL of a publicly-accessible webpage to pay for the order. */
    public private(set) var paymentUrl: String?
    /** A URL of a publicly-accessible webpage to see the order's status. */
    public private(set) var statusUrl: String?
    /** Indicates if the current user is allowed to download content from the attached listing. */
    public private(set) var downloadsAllowed: Bool?
    /** Indicates if the current user is allowed to make a payment for the order. */
    public private(set) var paymentsAllowed: Bool?
    public private(set) var address: Address?
    public private(set) var customer: Group?
    public private(set) var listing: Listing?
    /** items */
    public private(set) var items: [OrderItem]?
    public private(set) var appointments: [Appointment]?
    public private(set) var unconfirmedAppointments: [UnconfirmedAppointment]?

    public init(id: UUID, number: Int, title: String, fulfillmentStatus: FulfillmentStatus, paymentStatus: PaymentStatus, currency: Currency? = nil, totalAmount: Int? = nil, paymentUrl: String? = nil, statusUrl: String?, downloadsAllowed: Bool? = nil, paymentsAllowed: Bool? = nil, address: Address? = nil, customer: Group? = nil, listing: Listing? = nil, items: [OrderItem]? = nil, appointments: [Appointment]? = nil, unconfirmedAppointments: [UnconfirmedAppointment]? = nil) {
        self.id = id
        self.number = number
        self.title = title
        self.fulfillmentStatus = fulfillmentStatus
        self.paymentStatus = paymentStatus
        self.currency = currency
        self.totalAmount = totalAmount
        self.paymentUrl = paymentUrl
        self.statusUrl = statusUrl
        self.downloadsAllowed = downloadsAllowed
        self.paymentsAllowed = paymentsAllowed
        self.address = address
        self.customer = customer
        self.listing = listing
        self.items = items
        self.appointments = appointments
        self.unconfirmedAppointments = unconfirmedAppointments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case number
        case title
        case fulfillmentStatus = "fulfillment_status"
        case paymentStatus = "payment_status"
        case currency
        case totalAmount = "total_amount"
        case paymentUrl = "payment_url"
        case statusUrl = "status_url"
        case downloadsAllowed = "downloads_allowed"
        case paymentsAllowed = "payments_allowed"
        case address
        case customer
        case listing
        case items
        case appointments
        case unconfirmedAppointments = "unconfirmed_appointments"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(number, forKey: .number)
        try container.encode(title, forKey: .title)
        try container.encode(fulfillmentStatus, forKey: .fulfillmentStatus)
        try container.encode(paymentStatus, forKey: .paymentStatus)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(totalAmount, forKey: .totalAmount)
        try container.encodeIfPresent(paymentUrl, forKey: .paymentUrl)
        try container.encode(statusUrl, forKey: .statusUrl)
        try container.encodeIfPresent(downloadsAllowed, forKey: .downloadsAllowed)
        try container.encodeIfPresent(paymentsAllowed, forKey: .paymentsAllowed)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(customer, forKey: .customer)
        try container.encodeIfPresent(listing, forKey: .listing)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(appointments, forKey: .appointments)
        try container.encodeIfPresent(unconfirmedAppointments, forKey: .unconfirmedAppointments)
    }
}

