//
// PaginationLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Related links for a paginated response. */
public struct PaginationLinks: Codable {

    /** The first page. */
    public private(set) var first: String
    /** The last page. */
    public private(set) var last: String
    /** The previous page. This is specified as either `string` or `null` purely for spec testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand. */
    public private(set) var prev: String?
    /** The next page. This is specified as either `string` or `null` purely for spec testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand. */
    public private(set) var next: String?

    public init(first: String, last: String, prev: String? = nil, next: String? = nil) {
        self.first = first
        self.last = last
        self.prev = prev
        self.next = next
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case first
        case last
        case prev
        case next
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(first, forKey: .first)
        try container.encode(last, forKey: .last)
        try container.encodeIfPresent(prev, forKey: .prev)
        try container.encodeIfPresent(next, forKey: .next)
    }
}

