//
// PartialGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A collection of users that can interact with the Aryeo platform. Permissions and properties are determined based on the type which can be creator, agent, or brokerage. */
public struct PartialGroup: Codable, Hashable {

    public enum GroupType: String, Codable, CaseIterable {
        case creator = "creator"
        case agent = "agent"
        case brokerage = "brokerage"
    }
    /** ID of the group. */
    public var id: UUID
    /** The type of group. */
    public var groupType: GroupType
    /** The name of the group. */
    public var name: String
    /** Group logo. */
    public var logo: String?
    /** Email. */
    public var email: String?
    /** Phone number. */
    public var phone: String?
    /** Does this group represent a brokerage or an agent who belongs to a brokerage? */
    public var isBrokerageOrBrokerageAgent: Bool

    public init(id: UUID, groupType: GroupType, name: String, logo: String? = nil, email: String? = nil, phone: String? = nil, isBrokerageOrBrokerageAgent: Bool) {
        self.id = id
        self.groupType = groupType
        self.name = name
        self.logo = logo
        self.email = email
        self.phone = phone
        self.isBrokerageOrBrokerageAgent = isBrokerageOrBrokerageAgent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case groupType = "group_type"
        case name
        case logo
        case email
        case phone
        case isBrokerageOrBrokerageAgent = "is_brokerage_or_brokerage_agent"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(groupType, forKey: .groupType)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(logo, forKey: .logo)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encode(isBrokerageOrBrokerageAgent, forKey: .isBrokerageOrBrokerageAgent)
    }
}

