//
// ProductCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A category for products. */
public struct ProductCategory: Codable {

    /** ID of the product category. UUID Version 4. */
    public private(set) var id: UUID
    /** The title of the product category. */
    public private(set) var title: String

    public init(id: UUID, title: String) {
        self.id = id
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
    }
}

