//
// PropertyWebsite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Website (in branded and unbranded versions) that displays information about a property. */
public struct PropertyWebsite: Codable {

    /** ID of the website. UUID Version 4. */
    public private(set) var id: UUID
    /** URL for branded version of website. */
    public private(set) var brandedUrl: String
    /** URL for unbranded version of website. */
    public private(set) var unbrandedUrl: String

    public init(id: UUID, brandedUrl: String, unbrandedUrl: String) {
        self.id = id
        self.brandedUrl = brandedUrl
        self.unbrandedUrl = unbrandedUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case brandedUrl = "branded_url"
        case unbrandedUrl = "unbranded_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(brandedUrl, forKey: .brandedUrl)
        try container.encode(unbrandedUrl, forKey: .unbrandedUrl)
    }
}

