//
// PropertyWebsites.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Websites that displays information about a property. */
public struct PropertyWebsites: Codable, Hashable {

    /** URL for website. */
    public var brandedUrl: String
    /** URL for website. */
    public var unbrandedUrl: String
    /** ID for property website */
    public var id: Int

    public init(brandedUrl: String, unbrandedUrl: String, id: Int) {
        self.brandedUrl = brandedUrl
        self.unbrandedUrl = unbrandedUrl
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brandedUrl = "branded_url"
        case unbrandedUrl = "unbranded_url"
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brandedUrl, forKey: .brandedUrl)
        try container.encode(unbrandedUrl, forKey: .unbrandedUrl)
        try container.encode(id, forKey: .id)
    }
}

