//
// Timeslot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A bookable time range, including users that are available. */
public struct Timeslot: Codable {

    /** Start time of the available slot */
    public private(set) var startAt: String
    /** End time of the available slot */
    public private(set) var endAt: String
    public private(set) var users: [User]?

    public init(startAt: String, endAt: String, users: [User]? = nil) {
        self.startAt = startAt
        self.endAt = endAt
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startAt = "start_at"
        case endAt = "end_at"
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(startAt, forKey: .startAt)
        try container.encode(endAt, forKey: .endAt)
        try container.encodeIfPresent(users, forKey: .users)
    }
}

